---
title: "Reading reactions"
---

You should actively participate in class, do all the readings, and discuss them outside of class. 

To encourage engagement with the course content—and to allow me to collect the class's questions each week—you'll need to engage with the readings on Perusall. You should provide comments and reactions to at least nine of our ten weeks of reading assignments. You may (and should) also engage with questions you see posted by others. However, it'll be up to me to decide whether a comment engages with the assigned reading and adds to the discussion, meaningfully.

As you're working through the content, I want to hear about what you're learning and what questions you still have. These questions are **crucial** for our in-class discussions. Your reactions are **due by 11:55 PM on the day before class**. This is so I can look through the responses and start structuring the discussion for our class.

**You will provide your reading reactions via Perusall**, not Canvas. Your reactions consist of comments and discussions on Perusall (they are not essay-based, and there is no formal submission). We will also use Perusall as a class chatroom, and so everyone can see my answers to any questions you may have for me. I'm sure you won't be the only one with your questions!

Your comments and reactions should allow me to answer two questions:

1. What were the **two (2)** most interesting or exciting things you learned? Why?
2. What were the **two (2)** muddiest or unclear things? What are you still wondering about?    

You can point out more than two interesting or muddiest things, but you must include at least two. There should be four easily identifiable things in your comments: two exciting things and two questions.

I will grade your reactions and comments using a check system:

- ✔+: (*1.1 point*) Your comments show phenomenal thought and engagement with the course content. You also showed exceptional effort to help others. I will not assign these often.
- ✔: (*1 point*) Your comments are thoughtful, well-written, and show engagement with the course content. You also helped others. This is the expected level of performance.
- ✔−: (*0.5 point*) Your comments are hastily composed and/or only cursorily engage with the course content. This grade signals that you need to improve next time. I will hopefully not assign these often.

This is essentially a pass/fail or completion-based system. I'm not grading your writing ability, and I'm not counting the exact number of words you're writing in your comments. I'm looking for thoughtful engagement, two interesting things, and two questions. That's all. Do good work and you'll get a ✓.
