project:
  type: website
  render:
    - "*.qmd"
    - "!slides/"
    - "!projects/"
  resources:
    - "files/"
    - "projects/"
    - "slides/*.html"
    - "slides/*.pdf"
    - "slides/img/"
    - "slides/libs/"
    - "slides/css/"
    - "slides/*_files/"
  preview:
    port: 3333

execute:
  freeze: auto  # Re-render only when source changes

bibliography: files/bib/references.bib
csl: files/bib/chicago-author-date.csl

website:
  title: "EDUC 265"
  description: "Apply regression analysis to investigate causal relationships"
  site-url: "https://educ265.de-barros.com/"

  favicon: "/files/icon-512.png"

  twitter-card:
    image: "/files/social-image-f22.png"
    card-style: summary_large_image
    creator: "@andydebarros"
    # site: "@andydebarros"

  open-graph:
    image: "/files/social-image-f22.png"
    locale: en_US

  repo-url: "https://github.com/de-barros/educ265-25"
  repo-actions: [edit, issue]

  page-navigation: true

  navbar:
    pinned: true
    background: "#EE6A24"
    right:
      - syllabus.qmd
      - schedule.qmd
      - text: "Content"
        file: content/index.qmd
      - text: "Assignments"
        file: assignment/index.qmd
      - text: "Examples"
        file: example/index.qmd
      - text: "Resources"
        file: resource/index.qmd
      - text: "News & FAQs"
        file: news/index.qmd
      - icon: slack
        href: "https://gsuevalsp2024.slack.com"
        aria-label: Slack
      - icon: cloud-fill
        href: "https://posit.cloud"
        aria-label: Posit.cloud

  sidebar:
    - title: "Content"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Overview"
          contents:
            - content/index.qmd
        - section: "Course content"
          contents:
            - text: "1: The causal revolution"
              file: content/01-content.qmd
            - text: "2: Review of regression analysis"
              file: content/02-content.qmd
            - text: "3: Interactions and transformations"
              file: content/03-content.qmd
            - text: "4: Discrete outcomes and regression adjustment"
              file: content/04-content.qmd
            - text: "5: Fixed effects, value added, and randomized experiments"
              file: content/05-content.qmd
            - text: "6: Sample size calculations and clustered data"
              file: content/06-content.qmd
            - text: "7: Instrumental variables"
              file: content/07-content.qmd
            - text: "8: Regression discontinuity"
              file: content/08-content.qmd
            - text: "9: Difference in differences"
              file: content/09-content.qmd
            - text: "10: Open science and multiple hypothesis testing"
              file: content/10-content.qmd

    - title: "Assignments"
      contents:
        - section: "Overview"
          contents:
            - assignment/index.qmd
        - section: "Other projects"
          contents:
            - assignment/final-project.qmd
            - assignment/weekly-check-in.qmd
        - section: "Problem sets"
          contents:
            - assignment/01-problem-set.qmd
            - assignment/02-problem-set.qmd
            - assignment/03-problem-set.qmd
            - assignment/04-problem-set.qmd
            - assignment/05-problem-set.qmd
            - assignment/06-problem-set.qmd
            - assignment/07-problem-set.qmd
            - assignment/08-problem-set.qmd
            - assignment/09-problem-set.qmd
        - section: "Evaluation"
          contents:
            - assignment/01-eval-background-theory.qmd
            - assignment/02-eval-measurement.qmd
            - assignment/03-eval-dag.qmd
            - assignment/04-eval-threats.qmd

    - title: "Examples"
      contents:
        - section: "Overview"
          contents:
            - example/index.qmd
        - section: "Simulated data"
          contents:
            - text: "Random numbers"
              file: example/random-numbers.qmd
            - text: "Synthetic data"
              file: example/synthetic-data.qmd
        - section: "Examples"
          contents:
            - example/rstudio-tidyverse.qmd
            - example/regression.qmd
            - example/dags.qmd
            - example/po-ate-cate.qmd
            - text: "RCTs"
              file: example/rcts.qmd
            - text: "Matching and IPW"
              file: example/matching-ipw.qmd
            - text: "Robust standard errors"
              file: example/standard-errors.qmd
            - text: "Unobserved confounding"
              file: example/confounding-sensitivity.qmd
            - text: "Diff-in-diff"
              file: example/diff-in-diff.qmd
            - example/rdd.qmd
            - example/iv.qmd
            - text: "ITT and CACE"
              file: example/cace.qmd
            - example/rdd-fuzzy.qmd

    - title: "Resources"
      contents:
        - section: "Resources"
          contents:
            - resource/index.qmd
            - resource/r.qmd
            - resource/style.qmd
            - resource/data.qmd
            - resource/citations.qmd
            - resource/bayes.qmd
            - resource/zilch.qmd
        - section: "Study guides"
          contents:
            - resource/exam1.qmd
            - resource/exam2.qmd
        - section: "Guides"
          contents:
            - resource/install.qmd
            - resource/markdown.qmd
            - resource/quarto.qmd
            - resource/unzipping.qmd

  page-footer:
    left: |
      Original content {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by [{{< var attribution.name_no_title >}}]({{< var attribution.url >}}) <br>
      Additional content {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}) <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: monokai
