---
title: "The causal revolution"
date: "2024-01-11"
---

```{r slides-videos, echo=FALSE, include=FALSE}
source(here::here("R", "slide-things.R"))
source(here::here("R", "youtube-playlist.R"))

playlist_id <- "PL-uRhZ_p-BM5ovNRg-G6hDib27OCvcyW8"

slide_details <- tibble::tribble(
  ~youtube_id,   ~title, ~slide, ~active,
  "WwW8y5dZs80", "Econometrics: The Path from Cause to Effect", "1", TRUE,
  "iPBV3BlV7jk", "Ceteris Paribus: Public vs. Private University", "magic-randomization", FALSE,
  "6YrIDhaUQOE", "Selection Bias: Will You Make More Going to a Private University?", "rct-how", FALSE
)
```

## Readings

- {{< fa file-pdf >}} *The Taboo Against Explicit Causal Inference in Nonexperimental Psychology* [@grosz_taboo_2020]
- {{< fa book >}} Chapters 4-7 in *The Effect* [@Huntington-Klein:2021]
- {{< fa book >}} Chapter 3 in *Impact Evaluation in Practice* [@wb-eval]

## Videos

```{r show-youtube-list, echo=FALSE, results="asis"}
youtube_list(slide_details, playlist_id)
```

## Slides

On the day of class, you will find my slides on Canvas. 
