---
title: "Instrumental variables"
date: "2024-02-22"
---

## Readings

- {{< fa book >}} Chapter 3 in *Mastering Metrics* (2015) [@AngristPischke:2015]
- ~~{{< fa book >}} Chapter 5 in *Impact Evaluation in Practice* [@wb-eval]~~
- {{< fa book >}} Chapter 19 in *The Effect* [@Huntington-Klein:2021]

```{r slides-videos, echo=FALSE, include=FALSE}
source(here::here("R", "slide-things.R"))
source(here::here("R", "youtube-playlist.R"))

playlist_id <- "PL-uRhZ_p-BM5ovNRg-G6hDib27OCvcyW8"

slide_details <- tibble::tribble(
  ~youtube_id,   ~title, ~slide, ~active,
  "eoJUPd6104Q", "Introduction to Instrumental Variables (IV)", "1", TRUE
)
```

## Videos

```{r show-youtube-list, echo=FALSE, results="asis"}
youtube_list(slide_details, playlist_id)
```   

<br>In addition, Videos 57-60 from [this](https://www.youtube.com/watch?v=SFI6mIvR-U0&list=PLVE5MzKQzt70JVDAmY42q9XR_V9oDUCyo&index=57) playlist accompany Chapter 19 in *The Effect*. Watching them is optional.

## Slides

On the day of class, you will find my slides on Canvas. 
