---
title: "Readings and slides"
---

## Before you start

Before you start, please make sure to review the [syllabus](/syllabus.qmd), [schedule](/schedule.qmd), [content](/content/index.qmd), and [assignments](/assignment/index.qmd) pages of our course.

## Readings

Each class session has a set of required readings that you should complete ***before*** our in-person meetings. Reading reactions are due at 11:55 PM on the day before class (via Perusall). 

## Videos 

I will assign short videos for some of our classes.

## Optional materials 

For most of the classes, I will provide you with ***optional*** materials. For example, the assigned readings from *The Effect* [@Huntington-Klein:2021] are complemented by videos summarizing the content. Optional means truly optional---while I believe this material can be incredibly helpful, you are not expected to read or watch it before class. 

## Slides

I will also post slides on the day of class. You may bring a printed copy. I may edit these slides and post a final version shortly after class. Please make sure to use this final version as you prepare for your assignments and the exam.  

