---
title: "Going beyond"
---

The "causal inference revolution" means our course materials are now commonly taught not only at education schools but also in other social sciences. They are also highly sought after by employers. 

Here are additional resources in case you would like to go beyond what we cover in class. You may also find it helpful to see someone else explain the same concept. 

## Other courses

1. [Andrew Heiss](https://www.andrewheiss.com/) teaches [phenomenal classes](https://www.andrewheiss.com/teaching/) at Georgia State University. In fact, much of our course builds on his materials. Go [here](https://evalsp23.classes.andrewheiss.com/) if you would like to review some of the materials we covered in class.

2. [Fiona Burlig](https://www.fionaburlig.com/) teaches a great [program evaluation class](https://www.fionaburlig.com/ppha-34600-2020) at the University of Chicago. During the pandemic, she put all of her lectures online. Go here if you are looking for a slightly more advanced class.

3. [Matt Blackwell](https://mattblackwell.org/) provides a great introduction to [data science for the social sciences](https://gov50-f23.github.io/). Go here if you are looking for a broader introduction to data analysis with R. 

4. [Paul Goldsmith-Pinkham](https://paulgp.github.io/) teaches [this](https://github.com/paulgp/applied-methods-phd) applied methods class at Yale---it looks great! All of his lecture recordings are online [here](https://www.youtube.com/playlist?list=PLWWcL1M3lLlojLTSVf2gGYQ_9TlPyPbiJ).

5. Within the PhD program at UCI's School of Education, [EDUC 287A](https://catalogue.uci.edu/search/?P=EDUC%20287A)  (Advanced Quantitative Data Analysis for Causal Inference) and [EDUC 287B](https://catalogue.uci.edu/search/?P=EDUC%20287B) (Causal Inference: Methods for Program Evaluation and Policy Research) build on our class.

## Other books

To recap, here are the main books we used in class:

- Rachel A. Gordon, *Regression Analysis for the Social Sciences* (Routledge, 2010). ([**Free UCI library access to the ebook**](https://docs.google.com/document/d/1dUe5jqWVOYnpxxYdvgPgjHCts3391ZB3dEn5MRSnDTg/edit?usp=sharing))

- Nick Huntington-Klein, *The Effect: An Introduction to Research Design and Causality* (CRC Press, 2021), <https://theeffectbook.net/>. ([**Free as a HTML version!**](https://theeffectbook.net/))

- Joshua Angrist and Jörn-Steffen Pischke, *Mastering 'Metrics: The Path from Cause to Effect* (Princeton University Press, 2014).

Then, we also covered a few chapters from the following books: 

- Rachel Glennerster and Kudzai Takavarasha, *Running Randomized Evaluations* (Princeton University Press, 2014), <https://press.princeton.edu/books/paperback/9780691159270/running-randomized-evaluations>.  

- Richard J. Murnane and John B. Willett, *Methods Matter* (Oxford University Press, 2011), <https://global.oup.com/academic/product/methods-matter-9780199753864>.


We did not cover three additional books--all three are great, but they are slightly more math heavy (esp. the last one).

- Scott Cunningham, *Causal Inference: The Mixtape* (Yale University Press, 2021), <https://mixtape.scunning.com/>. [**Free as a HTML version**](https://mixtape.scunning.com/), and with a nice collection of video guest lectures (or ["Mixtape Sessions"](https://github.com/Mixtape-Sessions/))

- Paul Glewwe and Petra Todd, *Impact Evaluation in International Development: Theory, Methods, and Practice* (The World Bank, 2022), <https://doi.org/10.1596/978-1-4648-1497-6>. [**Free online**](https://doi.org/10.1596/978-1-4648-1497-6)

- Joshua Angrist and Jörn-Steffen Pischke, *Mostly Harmless Econometrics* (Princeton University Press, 2014), <https://theeffectbook.net/>. [**This book also has a companion site**](https://www.mostlyharmlesseconometrics.com/)

If you are intrigued, there are *many* more excellent (more technical) books on causal inference, including [this one](https://www.cambridge.org/core/books/causal-inference-for-statistics-social-and-biomedical-sciences/71126BE90C58F1A431FE9B2DD07938AB) by Imbens and Rubin, [this](https://mitpress.mit.edu/9780262232586/econometric-analysis-of-cross-section-and-panel-data/) "classic" by Jeff Wooldridge, and the [J-PAL Handbook of Field Experiments](https://www.povertyactionlab.org/page/handbook-field-experiments).[^PhD] The most up-to-date (free!) book on Machine Learning and causal inference is [this](https://bookdown.org/stanfordgsbsilab/ml-ci-tutorial/) book by Susan Athey's Social Impact Lab at Stanford. 

[^PhD]: You can even win the [Nobel Prize](https://www.nobelprize.org/uploads/2021/10/advanced-economicsciencesprize2021.pdf) for the ["experimental approach to alleviating global poverty"](https://www.nobelprize.org/prizes/economic-sciences/2019/press-release/). And yet another one for ["answering causal questions using observational data"](https://www.nobelprize.org/uploads/2021/10/advanced-economicsciencesprize2021.pdf).

## Other research resources

I highly recommend the following online resources.

- J-PAL's [research resources](https://www.povertyactionlab.org/research-resources?view=toc) 
- The World Bank's [DIME Wiki](https://dimewiki.worldbank.org/Main_Page), its [Development Impact blog](https://blogs.worldbank.org/impactevaluations), and its curated [list of posts on technical topics](https://blogs.worldbank.org/impactevaluations/curated-list-our-postings-technical-topics-your-one-stop-shop-methodology-0)
- EGAP's [Methods Guides](https://egap.org/methods-guides/)
- MIT's ["MicroMasters" Program in Data, Economics, and Design of Policy](https://micromasters.mit.edu/dedp/)
- The IES What Works Clearinghouse [Standards Handbook](https://ies.ed.gov/ncee/wwc/Docs/referenceresources/WWC-Standards-Handbook-v4-1-508.pdf) 
- The IES [Standards for Excellence in Education Research](https://ies.ed.gov/seer/) 
