---
title: Data
---

There are a ton of places to find data related to education, public policy, and administration (as well as data on pretty much any topic you want) online:

- [**Data is Plural newsletter**](https://www.data-is-plural.com/): Jeremy Singer-Vine sends a weekly newsletter of the most interesting public datasets he's found. You should subscribe to it. [He also has an archive of all the datasets he's highlighted.](https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit#gid=0)

- [**Google Dataset Search**](https://toolbox.google.com/datasetsearch): Google indexes thousands of public datasets; search for them here.

- [**J-PAL Catalog of Administrative Datasets**](https://www.povertyactionlab.org/catalog-administrative-data-sets): To assist researchers in screening potential data sources, J-PAL North America has cataloged a number of key US data sets.

- [**Kaggle**](https://www.kaggle.com/datasets): Kaggle hosts machine learning competitions where people compete to create the fastest, most efficient, most predictive algorithms. A byproduct of these competitions is a host of fascinating datasets that are generally free and open to the public. See, for example, [the European Soccer Database](https://www.kaggle.com/hugomathien/soccer), the [Salem Witchcraft Dataset](https://www.kaggle.com/rtatman/salem-witchcraft-dataset) or results from an [Oreo flavors taste test](https://www.kaggle.com/rtatman/oreo-flavors-tastetest-ratings).

- [**360Giving**](http://www.threesixtygiving.org/data/data-registry/): Dozens of British foundations follow a standard file format for sharing grant data and have made that data available online.

- [**US City Open Data Census**](http://us-cities.survey.okfn.org/): More than 100 US cities have committed to sharing dozens of types of data, including data about crime, budgets, campaign finance, lobbying, transit, and zoning. This site from the [Sunlight Foundation](http://sunlightfoundation.com/) and [Code for America](http://www.codeforamerica.org//) collects this data and rates cities by how well they're doing.

- [**The Stanford Education Data Archive (SEDA)**](https://exhibits.stanford.edu/data/catalog/db586ns4974) is "an initiative aimed at harnessing data to help us—scholars, policymakers, educators, parents—learn how to improve educational opportunity for all children."

- [**The Common Core of Data (CCD)**](https://nces.ed.gov/ccd/) is "the Department of Education's primary database on public elementary and secondary education in the United States".
  
- Data from large-scale assessments such as [**NAEP**](https://nces.ed.gov/nationsreportcard/researchcenter/software.aspx), [**PISA**](https://www.oecd.org/pisa/), and [**TIMSS**](https://nces.ed.gov/timss/) and [**PIRLS**](https://nces.ed.gov/surveys/pirls/).

- **Replication files**: Many academic journals now require that data (and code) be posted online, along with an article.   
    - **Journal websites**: If you read an academic article online, look for "supplemental materials" or the article's "data appendix".
    - [**Harvard Dataverse**](https://dataverse.harvard.edu/dataverse/harvard): This repository includes thousands of datasets from academic articles, including [the repository](https://dataverse.harvard.edu/dataverse/jpal) for articles by J-PAL affiliates.
